# Device configurations

temperature_sensor:
  class: TemperatureSensor
  protocol: mqtt
  port: 1883
  mqtt:
    host: 127.0.0.1
    port: 1883
    topic: sensors/temperature
  initial_state: inactive
  scenarios:
    - overheat
    - disconnect

pressure_valve:
  class: PressureValve
  protocol: opcua
  port: 4840
  initial_state: inactive
  scenarios:
    - leak
    - jam
